# Basic Site Settings
title: My mathematics web site
description: "This site contains information pertaining to my mathematical work. "
baseurl: "" # Leave empty if your site is at username.github.io
url: "" # Your site's final URL

# Clean URLs (Removes .html from links)
permalink: /:basename/

# Tell Jekyll to include specific folders if needed
include:
  - .htaccess
  - documents/

# Exclude files you don't want on the live site
exclude:
  - README.md
  - .gitignore